kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "API Server"
paths = ["/api"]

[services.development]
run = "node index.js"

[services.production]

[services.production.build]
args = []

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "index.js"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/health"
